/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IpaChartIndexRouteImport } from './routes/ipa-chart/index'
import { Route as IpaChartSplatRouteImport } from './routes/ipa-chart/$'
import { Route as IpaChartConsonantsRouteImport } from './routes/ipa-chart/consonants'
import { Route as IpaChartVowelsRouteImport } from './routes/ipa-chart/vowels'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeTopicRouteImport } from './routes/practice.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IpaChartIndexRoute = IpaChartIndexRouteImport.update({
  id: '/ipa-chart/',
  path: '/ipa-chart/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpaChartSplatRoute = IpaChartSplatRouteImport.update({
  id: '/ipa-chart/$',
  path: '/ipa-chart/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IpaChartConsonantsRoute = IpaChartConsonantsRouteImport.update({
  id: '/ipa-chart/consonants',
  path: '/ipa-chart/consonants',
  getParentRoute: () => rootRouteImport,
} as any)
const IpaChartVowelsRoute = IpaChartVowelsRouteImport.update({
  id: '/ipa-chart/vowels',
  path: '/ipa-chart/vowels',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeTopicRoute = PracticeTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => PracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/practice': typeof PracticeRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ipa-chart/$': typeof IpaChartSplatRoute
  '/ipa-chart/consonants': typeof IpaChartConsonantsRoute
  '/ipa-chart/vowels': typeof IpaChartVowelsRoute
  '/ipa-chart/': typeof IpaChartIndexRoute
  '/practice/$topic': typeof PracticeTopicRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ipa-chart/$': typeof IpaChartSplatRoute
  '/ipa-chart/consonants': typeof IpaChartConsonantsRoute
  '/ipa-chart/vowels': typeof IpaChartVowelsRoute
  '/ipa-chart': typeof IpaChartIndexRoute
  '/practice/$topic': typeof PracticeTopicRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/practice': typeof PracticeRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ipa-chart/$': typeof IpaChartSplatRoute
  '/ipa-chart/consonants': typeof IpaChartConsonantsRoute
  '/ipa-chart/vowels': typeof IpaChartVowelsRoute
  '/ipa-chart/': typeof IpaChartIndexRoute
  '/practice/$topic': typeof PracticeTopicRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/practice'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ipa-chart/$'
    | '/ipa-chart/consonants'
    | '/ipa-chart/vowels'
    | '/ipa-chart/'
    | '/practice/$topic'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ipa-chart/$'
    | '/ipa-chart/consonants'
    | '/ipa-chart/vowels'
    | '/ipa-chart'
    | '/practice/$topic'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/credits'
    | '/practice'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ipa-chart/$'
    | '/ipa-chart/consonants'
    | '/ipa-chart/vowels'
    | '/ipa-chart/'
    | '/practice/$topic'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditsRoute: typeof CreditsRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IpaChartSplatRoute: typeof IpaChartSplatRoute
  IpaChartConsonantsRoute: typeof IpaChartConsonantsRoute
  IpaChartVowelsRoute: typeof IpaChartVowelsRoute
  IpaChartIndexRoute: typeof IpaChartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipa-chart/': {
      id: '/ipa-chart/'
      path: '/ipa-chart'
      fullPath: '/ipa-chart/'
      preLoaderRoute: typeof IpaChartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipa-chart/$': {
      id: '/ipa-chart/$'
      path: '/ipa-chart/$'
      fullPath: '/ipa-chart/$'
      preLoaderRoute: typeof IpaChartSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipa-chart/consonants': {
      id: '/ipa-chart/consonants'
      path: '/ipa-chart/consonants'
      fullPath: '/ipa-chart/consonants'
      preLoaderRoute: typeof IpaChartConsonantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipa-chart/vowels': {
      id: '/ipa-chart/vowels'
      path: '/ipa-chart/vowels'
      fullPath: '/ipa-chart/vowels'
      preLoaderRoute: typeof IpaChartVowelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/$topic': {
      id: '/practice/$topic'
      path: '/$topic'
      fullPath: '/practice/$topic'
      preLoaderRoute: typeof PracticeTopicRouteImport
      parentRoute: typeof PracticeRoute
    }
  }
}

interface PracticeRouteChildren {
  PracticeTopicRoute: typeof PracticeTopicRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeTopicRoute: PracticeTopicRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditsRoute: CreditsRoute,
  PracticeRoute: PracticeRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IpaChartSplatRoute: IpaChartSplatRoute,
  IpaChartConsonantsRoute: IpaChartConsonantsRoute,
  IpaChartVowelsRoute: IpaChartVowelsRoute,
  IpaChartIndexRoute: IpaChartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
