/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IpaChartRouteImport } from './routes/ipa-chart'
import { Route as IndexRouteImport } from './routes/index'

const IpaChartRoute = IpaChartRouteImport.update({
  id: '/ipa-chart',
  path: '/ipa-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ipa-chart': typeof IpaChartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ipa-chart': typeof IpaChartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ipa-chart': typeof IpaChartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ipa-chart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ipa-chart'
  id: '__root__' | '/' | '/ipa-chart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IpaChartRoute: typeof IpaChartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ipa-chart': {
      id: '/ipa-chart'
      path: '/ipa-chart'
      fullPath: '/ipa-chart'
      preLoaderRoute: typeof IpaChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IpaChartRoute: IpaChartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
